os: linux
language: python
cache: pip
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - TOX_ENV=py27
  - TOX_ENV=py35
  - TOX_ENV=py36
  - TOX_ENV=py37
  - TOX_ENV=py38
install:
  - pip install tox
script:
  - tox -e $TOX_ENV