name: Update data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 5" # run once a week at 00:00 on Friday.

jobs:
  resources:
    name: Update resources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-benedict
          pip install python-fsutil
          pip install python-slugify

      - name: Update data
        run: python ./scripts/updatedata.py

      - name: Commit data
        uses: test-room-7/action-update-file@v1
        with:
          file-path: ./codicefiscale/data/municipalities.json
          commit-msg: "Updated `municipalities.json` data."
          github-token: ${{ secrets.GITHUB_TOKEN }}
